Revamp most of the documentation
movie-web/docs pull request #14
Opened 2023-12-31 14:54 UTC by qtchaos

This PR includes a lot of controversial changes, this is just the first draft and anything can and most likely will be changed.

This revamp intends to:
1. Add better explanations to previously less explained parts of the documents.
2. Make the guides for self-hosting easier to understand/follow.
3. Add better links to the pages, allowing users to view configuration options quickly.
4. Add more troubleshooting steps.

Things I need to fix:
* Troubleshooting mentions `postgres.ssl` though this hasnt been merged yet, missing from config docs aswell.

Things I need opinions on:
* Config pages layout (types, defaults, etc)

2023-12-31 15:19 UTC, qtchaos commented
Netlify build seems broken :p

2023-12-31 15:27 UTC, binaryoverload commented
> Netlify build seems broken :p

Whoops, it'll update if you commit something again

2024-01-02 02:16 UTC, qtchaos commented
Mysterious errors in deploy preview console that don't appear when building locally.. not sure if it's something to worry about or not.

2024-01-03 16:07 UTC, mrjvs requested changes

2024-01-03 16:08 UTC, mrjvs commented
Looks good, some small changes in terms of content. but I like all of the changes made.

2024-01-03 18:46 UTC, qtchaos commented on content/1.self-hosting/4.troubleshooting.md
> -This is likely that you haven't installed the PWA version of movie-web. Please read the [upgrade guide](../3.client/5.upgrade.md)
Isn't it still there though?
![image](https://github.com/movie-web/docs/assets/72168435/7f1b8365-f411-455a-88e6-c03a64cb2ec5)

2024-01-03 18:52 UTC, qtchaos commented on content/4.backend/0.introduction.md
> +The backend is essentially just an account server, there is not much more to it. The client will work fine without it, but no syncing options will be available.
"The backend is essentially just an account server. It handles user accounts, syncing, and other account related features.", would this be better?

2024-01-03 18:55 UTC, qtchaos commented on content/3.client/0.introduction.md
> +The client can be optionally ran as a [PWA](https://web.dev/explore/progressive-web-apps), which allows it to be installed on a mobile device. This can be hard to do correctly and really hard to reve
![image](https://github.com/movie-web/docs/assets/72168435/684a18ab-89bf-421c-ae49-f416347f9af4)
Is this better?

2024-01-03 18:58 UTC, mrjvs commented on content/1.self-hosting/4.troubleshooting.md
> -This is likely that you haven't installed the PWA version of movie-web. Please read the [upgrade guide](../3.client/5.upgrade.md)
Oh yea, im a derp. readt the diff wrong

2024-01-03 18:58 UTC, mrjvs commented on content/4.backend/0.introduction.md
> +The backend is essentially just an account server, there is not much more to it. The client will work fine without it, but no syncing options will be available.
Yea, sounds good

2024-01-03 18:59 UTC, mrjvs commented on content/3.client/0.introduction.md
> +The client can be optionally ran as a [PWA](https://web.dev/explore/progressive-web-apps), which allows it to be installed on a mobile device. This can be hard to do correctly and really hard to reve
Yea, thats great.

2024-01-03 19:02 UTC, qtchaos commented on content/1.self-hosting/4.troubleshooting.md
> -This is likely that you haven't installed the PWA version of movie-web. Please read the [upgrade guide](../3.client/5.upgrade.md)
haha yeah, i didnt see it at first aswell

2024-01-03 19:04 UTC, mrjvs submitted a review, later dismissed

2024-01-03 19:04 UTC, mrjvs commented
@binaryoverload please review, your codeowner thingy

2024-01-03 19:16 UTC, binaryoverload requested changes

2024-01-03 19:16 UTC, binaryoverload commented on content/0.index.md
> +  We support syncing your progress, proxies and bookmarks across devices, so you can easily continue where you left off.
`continue where you left off` has been used in "Saves your progress" so maybe something like:
```suggestion
  Enjoy uninterrupted streaming as your progress, proxies, and bookmarks sync effortlessly across all your devices.
```

2024-01-03 19:16 UTC, binaryoverload commented on content/0.index.md
> +  Supports custom themes, subtitle colors and subtitle sizes so you can make it look however you want.
I'm wondering if this might give people the wrong idea about themes, as in they might think they can change the theme to literally anything - thoughts?

2024-01-03 19:16 UTC, binaryoverload commented on content/0.index.md
> +  Supports PWA, so you can install it on your phone and use it just like a native app.
I'd suggest having a non-abbreviated version, like so:
```suggestion
  Progressive Web App Support
  #description
  Supports PWA, so you can install it on your phone and use it just like a native app.
```

2024-01-03 19:16 UTC, binaryoverload commented on content/3.client/1.deploy.md
> +   - Etc, [there are lots of options](https://www.staticwebsitehosting.org/){target="\_blank"}.
Nice, didn't know that website was a thing!

2024-01-03 19:17 UTC, qtchaos commented on content/0.index.md
> +  Supports custom themes, subtitle colors and subtitle sizes so you can make it look however you want.
Maybe change to "various themes"

2024-01-03 19:17 UTC, binaryoverload commented on content/0.index.md
> +  Supports custom themes, subtitle colors and subtitle sizes so you can make it look however you want.
Yeah - I like that

2024-01-03 19:22 UTC, binaryoverload requested changes
The Americanisation breaks my little British heart <-- This isn't a request, ignore this

One last thing, could you edit the .github/CODEOWNERS file to match the [movie-web](https://github.com/movie-web/movie-web/blob/master/.github/CODEOWNERS) one please?

2024-01-03 19:24 UTC, binaryoverload approved these changes

2024-01-03 19:25 UTC, merged