Add guide on how to get best streams
movie-web/docs pull request #21
Opened 2024-01-10 19:49 UTC by qtchaos

Closes https://github.com/movie-web/movie-web/issues/758.

* Adds a new "Extra" category meant to be used for extra topics, so that we can link to them in the Discord, etc.
* Wrote a small section for all the current supported ways to proxy requests (+ extension) so that users have a bit more context.
* Removes the `Edit page on GitHub` button, I felt as it got in the way more than it helped and incentivizes random docs changes rather than proper PRs with approved issues.

2024-01-10 19:56 UTC, JorrinKievit commented on content/5.extra/1.streaming.md
> +This method is great if you only use movie-web on your computer. If you use a mobile device or smart TV, you'll unfortunately have to stick to using a proxy since these devices don't usually support
Firefox mobile (only for android) will also work (hopefully) https://addons.mozilla.org/en-US/android/

2024-01-10 19:58 UTC, qtchaos commented on content/5.extra/1.streaming.md
> +This method is great if you only use movie-web on your computer. If you use a mobile device or smart TV, you'll unfortunately have to stick to using a proxy since these devices don't usually support
Ah yeah, thought about that but wasn't sure if that was something that will be supported or not :)

2024-01-10 19:59 UTC, mrjvs requested changes

2024-01-10 19:59 UTC, mrjvs commented on content/5.extra/1.streaming.md
> +Once you follow the guide on how to set up a proxy, you can use the URL of your proxy in the client either by using the [`VITE_CORS_PROXY_URL`](../3.client/3.configuration.md#vite_cors_proxy_url) var
I like it, but I think it should contain a list of steps to get the self-hosted proxy in the right place.
The goal of the page is to inform the user of the best ways to get streams, and how to actually get it setup.
So if somehow whines about having buffering, we can link this page and they wouldn't need any extra help.

Something like:

```md
...Selfhost proxy gives access to faster streams than default..

...To deploy follow this steps:...
1. Setup a proxy on netlify: ../2.proxy/1.deploy.md
2. Go to settings page on movie-web (link to it)
3. Enabled "custom proxy urls" if its not already
4. Click "add new url" if there isn't one (show screenshot of completed settings page)
5. Copy netlify URL (show image on how to)

::alert
...If you're selfhosting, you can input this URL in VITE_CORS_PROXY_URL.
::
```

2024-01-10 19:59 UTC, mrjvs commented on content/5.extra/1.streaming.md
> +If you are using the main website, then you are most likely already using the public proxy. This is not the case with self-hosted clients, there is no proxy set up by default on self-hosted clients a
We should probably mention the cons of using the public proxy.
It has slower streams and buffers quite often.

2024-01-10 23:32 UTC, qtchaos commented
Should probably link back to the Streaming guide from the proxy deploy guides so that it  actually shows how to set up the client.

2024-01-11 22:18 UTC, mrjvs approved these changes

2024-01-11 22:19 UTC, merged