Update client docs - 3rd option docker compose
movie-web/docs pull request #32
Opened 2024-02-28 03:23 UTC by Audiosutras

This PR is to add a 3rd option, `docker-compose` to client deployment.

2024-02-28 13:08 UTC, Audiosutras commented
I did not mention port forwarding from the router to make MWA reachable from the open internet. I would uncomfortable recommending this to an end user with minimum knowledge.

2024-02-29 23:23 UTC, binaryoverload commented
After some research, it turns out that you can use a build context from a Git URL i.e.

```yml
build:
  context: https://github.com/movie-web/movie-web.git
```

So I think the best thing to do is include a stripped-down version of the docker-compose.yml file we have in the repo in the docs, with only the common args

That way people don't have to clone the repo

2024-03-01 00:14 UTC, Audiosutras commented
@binaryoverload 😛 `dbDVwrTqQC3JxFmS4Uq5`

2024-03-01 00:35 UTC, Audiosutras commented
> After some research, it turns out that you can use a build context from a Git URL i.e.
> 
> ```yaml
> build:
>   context: https://github.com/movie-web/movie-web.git
> ```
> 
> So I think the best thing to do is include a stripped-down version of the docker-compose.yml file we have in the repo in the docs, with only the common args
> 
> That way people don't have to clone the repo

Great to know! Changed in docs.

2024-03-03 23:26 UTC, binaryoverload requested changes

2024-03-03 23:26 UTC, binaryoverload commented on content/3.client/1.deploy.md
> +$ docker compose up -d
I don't think you need to stop and remove, I think adding `--build` to the `up` command will suffice

2024-03-03 23:26 UTC, binaryoverload commented on content/3.client/1.deploy.md
> +      #   TURNSTILE_KEY: ""
Maybe just have a couple in here as examples, and then link to the config section for the rest? 

Might be worth updating the config page to also mention about these

2024-03-03 23:28 UTC, binaryoverload requested changes

2024-03-03 23:28 UTC, binaryoverload commented on content/3.client/1.deploy.md
> +version: "3.8"
It shouldn't cause a problem, but I generally specify a version like `3.2` to ensure maximum compatibility 

```suggestion
version: "3.2"
```

2024-03-05 14:10 UTC, Audiosutras commented on content/3.client/1.deploy.md
> +$ docker compose up -d
:heavy_check_mark:

2024-03-05 14:12 UTC, Audiosutras commented on content/3.client/1.deploy.md
> +      #   TURNSTILE_KEY: ""
See Step 5.

2024-03-05 14:12 UTC, Audiosutras commented on content/3.client/1.deploy.md
> +      #   TURNSTILE_KEY: ""
Reduced to tmdb, proxy, backend_url

2024-03-05 18:50 UTC, binaryoverload approved these changes

2024-03-05 18:50 UTC, merged