Update 1.deploy.md add more info
movie-web/docs pull request #48
Opened 2024-03-04 03:47 UTC by Pokeylooted

Add more thorough guide for selfhosting

2024-03-04 23:18 UTC, Pokeylooted commented
@binaryoverload Looks better now?

2024-03-04 23:25 UTC, binaryoverload requested changes

2024-03-04 23:25 UTC, binaryoverload commented on content/4.backend/1.deploy.md
> +**Congratulations!** You've successfully deployed the backend. Proceed to [set up the client](../1.self-hosting/2.use-backend.md).
Duplicated Railway section

2024-03-04 23:25 UTC, binaryoverload commented on content/4.backend/1.deploy.md
> +        ports:
I'd recommend adding this, it fixes some migration issues on certain platforms

```suggestion
          MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
          MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true" 
        ports:
```

2024-03-04 23:41 UTC, Pokeylooted commented on content/4.backend/1.deploy.md
> +**Congratulations!** You've successfully deployed the backend. Proceed to [set up the client](../1.self-hosting/2.use-backend.md).
Fixed mb

2024-03-04 23:45 UTC, Pokeylooted commented
@binaryoverload What do you think about adding a section for cloudflare argo tunnel? Too much to add onto docs?

2024-03-04 23:54 UTC, Pokeylooted reviewed
Should've fixed it now

2024-03-05 00:06 UTC, binaryoverload commented
> @binaryoverload What do you think about adding a section for cloudflare argo tunnel? Too much to add onto docs?

@Pokeylooted I think just change the `cloudflared tunnel` text to have a link to the docs on it

2024-03-05 00:08 UTC, binaryoverload requested changes

2024-03-05 00:08 UTC, binaryoverload commented on content/4.backend/1.deploy.md
> +* If you do use a reverse proxy, you may need to add `MWB_SERVER__CORS: "example.com movie.example.com"`.
```suggestion
* If you use a reverse proxy behind a domain, add `MWB_SERVER__CORS: "https://movie.example.com"`.
  - MWB_SERVER_CORS must contain a **space separated** list of origins (Protocol + Hostname) for the client to be able to access the backend.
```

2024-03-05 00:18 UTC, binaryoverload submitted a review, later dismissed
Looks good, thanks for your effort!

2024-03-05 00:19 UTC, binaryoverload approved these changes

2024-03-05 00:19 UTC, merged