Created 2.selfhost.md
movie-web/docs pull request #58
Opened 2024-03-20 07:50 UTC by Pokeylooted

Added a docker compose file that hosted all of movie-web, just to encourage more selfhosting and have a more straightforward way defined for people selfhosting.

2024-03-20 08:18 UTC, lonelil commented
you don't need to add the backend url for cors for the backend, only the frontend.

2024-03-20 09:44 UTC, Pokeylooted commented
> you don't need to add the backend url for cors for the backend, only the frontend.

Speaking of cors, do you know the cors situation on the proxy? I've had mixed results hosting it on that sometimes I have cors problems sometimes I don't

2024-03-25 23:26 UTC, binaryoverload requested changes
Overall good, just a few comments :)

2024-03-25 23:26 UTC, binaryoverload commented on content/5.extra/2.selfhost.md
> +### Guide to full Self-Deployment of Movie-Web with Docker Compose
```suggestion
### Guide to full Self-Deployment of movie-web with Docker Compose
```

Sorry to be pedantic :P

2024-03-25 23:26 UTC, binaryoverload commented on content/5.extra/2.selfhost.md
> +         - "5432:5432"
I don't think we need to expose the ports here, the backend can access it regardless as they are on the same network

2024-03-25 23:26 UTC, binaryoverload commented on content/5.extra/2.selfhost.md
> +     movie-web:
```suggestion
     movie-web-backend:
```

2024-03-27 21:56 UTC, Pokeylooted commented
Should be good to go now

2024-03-30 08:59 UTC, binaryoverload commented on content/5.extra/2.selfhost.md
> +         MWB_SERVER__TRUSTCLOUDFLARE: "true"
```suggestion
         MWB_SERVER__TRUSTCLOUDFLARE: "true"
         # This is needed to resolve errors running migrations on some platforms - does not affect the application 
         MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true"
```

2024-03-30 09:00 UTC, binaryoverload commented on content/5.extra/2.selfhost.md
> +         MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true"
```suggestion
         MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "false"
```

2024-03-30 09:01 UTC, binaryoverload commented on content/5.extra/2.selfhost.md
> +       image: ghcr.io/movie-web/simple-proxy:2.1.4
```suggestion
       image: ghcr.io/movie-web/simple-proxy:latest
```

2024-03-30 09:01 UTC, binaryoverload approved these changes

2024-03-30 09:02 UTC, merged