Add "Keeping your instance synced" section to "Upgrade Guide" page
movie-web/docs pull request #59
Opened 2024-03-22 16:19 UTC by sussy-code

[Discord Context](https://discord.com/channels/871713465100816424/871713465578979351/1220747802225934417), Adds a guide with 2 ways to keep an instance up to date.

2024-03-22 16:32 UTC, zisra approved these changes

2024-03-22 17:53 UTC, JorrinKievit commented on content/3.client/5.upgrade.md
> +Movie-web's github is constantly being updated. If you want to keep your instance synced to the most recent version, you will need to follow one of the two guides below.
```suggestion
Keeping your instance up-to-date with the latest features and bug fixes can enhance your instance's functionality and ensure it stays current. When updates are released, you have the option to adopt them using either one of the guides. Below, you willl find a manual and an automatic guide for updating your instance.
```

2024-03-22 17:53 UTC, JorrinKievit commented on content/3.client/5.upgrade.md
> +You can manually update by typing the below lines into a terminal at the root of your instance
```suggestion
You can manually update by executing the following commands at the root of your instance:
```

2024-03-22 17:53 UTC, JorrinKievit commented on content/3.client/5.upgrade.md
> +        github_token: ${{ secrets.PAT }}
Can't the automatic secret GITHUB_TOKEN be used here? https://docs.github.com/en/actions/security-guides/automatic-token-authentication

2024-03-23 00:47 UTC, sussy-code commented on content/3.client/5.upgrade.md
> +        github_token: ${{ secrets.PAT }}
Changed yaml file to the below snippet
```yaml
# File: .github/workflows/sync.yml
name: Sync fork

on:
  schedule:
  - cron: "*/5 * * * *"
  push:
    branches:
    - "*"
    paths:
    - .github/workflows/sync.yml

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: gh repo sync reponame/forkname
      env:
        GH_TOKEN: ${{ github.token }}
    - uses: gautamkrishnar/keepalive-workflow@v1
```

2024-03-23 16:02 UTC, sussy-code commented
pls merge

2024-03-25 23:00 UTC, binaryoverload requested changes
Thanks for this

As the primary recommendation, I would like people to fork the repo instead as it's a much less error prone method of keeping up to date. Would you be willing to update this page and the client setup page to include that?

2024-03-26 00:18 UTC, sussy-code commented on content/3.client/5.upgrade.md
> +You can manually update by executing the following commands at the root of your instance:
You can manually update by executing the following commands in the root directory of the repository you have created?

2024-03-26 00:20 UTC, sussy-code commented on content/3.client/5.upgrade.md
> +git push -f # Force push to your origin main branch
The git push -f command is necessary due to the --allow-unrelated-histories option in the git merge command.

2024-03-30 09:05 UTC, binaryoverload requested changes

2024-03-30 09:05 UTC, binaryoverload commented on content/3.client/5.upgrade.md
> +Github action authored by [Toon](https://github.com/Toon-arch)
Remove this please, it's irrelevant to the docs

2024-03-30 11:50 UTC, binaryoverload commented on content/3.client/5.upgrade.md
> +::
```suggestion
```

2024-03-30 11:51 UTC, binaryoverload approved these changes

2024-03-30 11:51 UTC, merged