I Improved Method 1 to enable Automatic update of the user's Instance.
movie-web/docs pull request #71
Opened 2024-04-06 17:00 UTC by superlincoln953

This improved method 1 will ensure that the user's self-hosted instance will be up-to-date with the latest features and bug fixes if the user set it up correctly.

2024-04-06 19:01 UTC, binaryoverload requested changes
While I agree with the sentiment, I feel like it would be better to remove the Vercel deploy button and just tell people how to set it up from scratch with a fork

This method would leave them with 2 repositories

2024-04-07 07:03 UTC, superlincoln953 commented
I removed the Vercel deploy button and told people how to set it up from scratch with a fork

2024-04-07 08:43 UTC, binaryoverload commented on pages/client/deploy.mdx
> +1. Click [here](https://vercel.com/)to go to Vercel
```suggestion
1. Click [here](https://vercel.com/) to go to Vercel
```

2024-04-07 08:44 UTC, binaryoverload approved these changes

2024-04-07 08:44 UTC, binaryoverload commented
Great, thanks

2024-04-07 08:45 UTC, merged